### ISSUE TITLE
Add some documentation

### ISSUE THREAD

**Issue by n0p** [BatchDrake/sigutils#1]
Please? :D

**Comment by BatchDrake** [comment]
I think it's way too early to write any documentation (not all blocks are implemented, and their implementation is subject to change depending on what I consider handier). But as soon as I'm able to demodulate stuff with this library I will write down some details on the API. There are better libraries to do what I do here, though.

**Comment by JulioSDDR** [comment]
Any updates? Do you want some [guided] help?

**Comment by BatchDrake** [comment]
I think it would be great to start documenting sigutils using something like https://readthedocs.org/

**Comment by antoniovazquezblanco** [comment]
I have read a little bit on how to do this.

ReadTheDocs seems to rely on sphinx to generate the documentation. The first step towards this would be to setup sphinx.

Some tasks that may help towars that:
- Creating a module to locate Sphinx
- Creating a CMakeFileList.txt in the doc folder that locates sphinx and setups a doc target if found.

See:
https://www.sphinx-doc.org/en/master/usage/quickstart.html
https://github.com/k0ekk0ek/cmake-sphinx/tree/master

**Comment by antoniovazquezblanco** [comment]
There is a WIP implementation of this. I cannot assing myself to the issue but I am working on it. There will be a PR soon :)

**Comment by antoniovazquezblanco** [comment]
Initial doxygen deployment now available at https://batchdrake.github.io/sigutils/.

**Comment by antoniovazquezblanco** [comment]
Documentation coverage reports are available and first steps towards documenting are being done in https://github.com/BatchDrake/sigutils/pull/66.

I understand that this is far away from a well rounded documentation but the mechanisms to document are in place. Should this issue be considered closed?

**Comment by antoniovazquezblanco** [comment]
The initial documentation infrastructure is in place. Could this be considered done?

**Comment by BatchDrake** [comment]
Assuming done due to inactivity.
