### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by mehdideveloper** [BatchDrake/sigutils#15]
Hey @BatchDrake 
Continuing my macOS tests, I tried to build everything from scratch on a fresh laptop to make sure it can be compiled on macOS in a straightforward manner. 
So I grabbed sigutils first and then installed libsndfile and fftw and pkg-config using brew and then tried to build the code.
I got a linker error and here's the output. By the way this is a fresh laptop without previous versions of sigutils or fftw etc. I will fix it and continue the build process (and then go to SigDigger) but I thought it would be good to document these issue as they happen, so we can track the order and history of build issues.
> 
> [ 65%] Linking C shared library libsigutils.dylib
> Undefined symbols for architecture x86_64:
>   "_fftwf_destroy_plan", referenced from:
>       _su_channel_detector_destroy in detect.c.o
>       _su_specttuner_destroy in specttuner.c.o
>       _su_specttuner_channel_destroy in specttuner.c.o
>   "_fftwf_execute", referenced from:
>       _su_channel_detector_feed_internal in detect.c.o
>       _su_specttuner_update_channel_filter in specttuner.c.o
>       ___su_specttuner_feed_bulk in specttuner.c.o
>       ___su_specttuner_feed_channel in specttuner.c.o
>   "_fftwf_free", referenced from:
>       _su_channel_detector_destroy in detect.c.o
>       _su_specttuner_destroy in specttuner.c.o
>       _su_specttuner_channel_destroy in specttuner.c.o
>   "_fftwf_malloc", referenced from:
>       _su_channel_detector_new in detect.c.o
>       _su_specttuner_new in specttuner.c.o
>       _su_specttuner_channel_new in specttuner.c.o
>   "_fftwf_plan_dft_1d", referenced from:
>       _su_channel_detector_new in detect.c.o
>       _su_specttuner_new in specttuner.c.o
>       _su_specttuner_channel_new in specttuner.c.o
>       _su_specttuner_init_filter_response in specttuner.c.o
>   "_sf_close", referenced from:
>       _su_wavfile_close in wavfile.c.o
>   "_sf_error", referenced from:
>       _su_block_wavfile_acquire in wavfile.c.o
>   "_sf_open", referenced from:
>       _su_wavfile_open in wavfile.c.o
>   "_sf_read_float", referenced from:
>       _su_block_wavfile_acquire in wavfile.c.o
>   "_sf_strerror", referenced from:
>       _su_wavfile_open in wavfile.c.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [libsigutils.dylib] Error 1

**Comment by BatchDrake** [comment]
Totally agree! But I think this one, in particular, is actually a bug. Could you edit your CMakeLists.txt and replace:

```
target_include_directories(sigutils SYSTEM PUBLIC ${SNDFILE_INCLUDE_DIRS})
target_include_directories(sigutils SYSTEM PUBLIC ${FFTW3_INCLUDE_DIRS})
```

With:

```
target_include_directories(sigutils SYSTEM PUBLIC ${SNDFILE_INCLUDE_DIRS})
target_link_libraries(sigutils ${SNDFILE_LIBRARIES})

target_include_directories(sigutils SYSTEM PUBLIC ${FFTW3_INCLUDE_DIRS})
target_link_libraries(sigutils ${FFTW3_LIBRARIES})

target_link_libraries(sigutils ${CMAKE_THREAD_LIBS_INIT})
target_link_libraries(sigutils m)
```

And try again?

**Comment by mehdideveloper** [comment]
Now I get this:

```
[ 65%] Linking C shared library libsigutils.dylib
ld: library not found for -lsndfile
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libsigutils.dylib] Error 1
```


FYI  `pkgcfg_lib_SNDFILE_sndfile` is set to  `/usr/local/Cellar/libsndfile/1.0.28/lib/libsndfile.dylib`

**Comment by BatchDrake** [comment]
Just tried in my GNU/Linux with `pkgcfg_lib_SNDFILE_sndfile` and it works (both in targets `sigutils` and `sutests`). However, as in a future port to Windows we may not be able to rely on pkg-config, I'm reluctant to switch to this variable, at least before I completely understand why this is failing here.

Could you send me a copy of the file `CMakeFiles/sigutils.dir/link.txt`? It should be inside your build directory.

**Comment by mehdideveloper** [comment]
Ok so I fixed the issue. The link to the FFTW and Sndfile libraries was not in the path (I just installed them today via brew)
I added `-L/usr/local/Cellar/libsndfile/1.0.28/lib -L/usr/local/Cellar/fftw/3.3.8_1/lib` to `CMakeFiles/sigutils.dir/link.txt` and `CMakeFiles/sutest.dir/link.txt` and then everything compiled successfully (note that I had to add to both files otherwise sutest would fail with the same link error)

**Comment by BatchDrake** [comment]
Still, having to modify link.txt by hand is still a kludge, this should compile out of the box. I'm marking this as a build-issue and look into it later.

**Comment by BatchDrake** [comment]
Hey, just wanted to tell you that I finally had some time to boot my VM and reproduce this failure. I'll try to fix this at dinner time.

**Comment by BatchDrake** [comment]
This should be fixed now. Pull both sigutils and suscan from `develop` (not from `master`!) and try again.

**Comment by mehdideveloper** [comment]
I can confirm that building from `develop` works without issues 👍
