### ISSUE TITLE
segfault after changing demodulation type

### ISSUE THREAD

**Issue by jedi7** [BatchDrake/sigutils#24]
All build from "develop" branch. 
* Gcc version: 11.1.0
* distribution: Archlinux
* RTL-SDR used with SoapyRemote
* sigutils: 58ac322c7224e17970e8ac7c89f42adb2208f07f
* suscan: 043a0bebbde0894ea57c73c7a965714011dcce7d
* suwidgets: 7e0dd63eacaea988f6da5f34a94829e8d6b89c80
* SigDigger: e919b5b545d43ae0e1ec56805408383a32004a75

Steps to reproduce:
0) Proposal: run with valgrind.  
1) turn on device
2) start switching between FM, LSB, USB .. mostly triggered here .. FM, AM

When use valgrind then probabily is always.
Seems there is not enough data to feed which leads to segfault. 
On valgrind if feeding is really slow, it happens really often. 
When running in normal mode it is less often (many changes of demodulation)

```
==794467== Memcheck, a memory error detector
==794467== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==794467== Using Valgrind-3.17.0 and LibVEX; rerun with -h for copyright info
==794467== Command: ./SigDigger
==794467==
[INFO] Opening Generic RTL2832U OEM :: 00000001...
[INFO] Opening Generic RTL2832U OEM :: 00000001...
[INFO] SoapyRemote::setupRxStream(remoteFormat=CS8, localFormat=CF32, scaleFactor=128, mtu=1500, window=44040192)
[INFO] Client side stream bound to 192.168.111.10:41894
[INFO] Client side status bound to 192.168.111.10:58138
[INFO] Using format CS8.
[INFO] Server side stream bound to [::ffff:192.168.111.4]:57891
[INFO] Server side stream connected to [::ffff:192.168.111.10]:41894
[INFO] Server side status connected to [::ffff:192.168.111.10]:58138
[INFO] Configured sender endpoint: dgram=1452 bytes, 714 elements @ 2 bytes, window=43008 KiB
[INFO] Client side stream connected to 192.168.111.4:57891
[INFO] Configured receiver endpoint: dgram=1452 bytes, 714 elements @ 2 bytes, window=43008 KiB
==794467==
==794467== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==794467==  General Protection Fault
==794467==    at 0x53789E8: ??? (in /usr/lib/libvolk.so.2.5.0)
==794467==    by 0x4991DBA: su_iir_filt_feed (in /usr/lib/libsigutils.so.0.3.0)
==794467==    by 0x4922260: suscan_audio_inspector_feed (in /usr/lib/libsuscan.so.0.3.0)
==794467==    by 0x491D233: suscan_inspector_sampler_loop (in /usr/lib/libsuscan.so.0.3.0)
==794467==    by 0x493FC92: ??? (in /usr/lib/libsuscan.so.0.3.0)
==794467==    by 0x4950155: ??? (in /usr/lib/libsuscan.so.0.3.0)
==794467==    by 0x6BDE258: start_thread (in /usr/lib/libpthread-2.33.so)
==794467==    by 0x706B5E2: clone (in /usr/lib/libc-2.33.so)
==794467==
==794467== HEAP SUMMARY:
==794467==     in use at exit: 67,624,208 bytes in 352,721 blocks
==794467==   total heap usage: 1,464,652 allocs, 1,111,931 frees, 9,233,569,895 bytes allocated
==794467==
==794467== LEAK SUMMARY:
==794467==    definitely lost: 1,683 bytes in 3 blocks
==794467==    indirectly lost: 2,932 bytes in 88 blocks
==794467==      possibly lost: 490,663 bytes in 2,665 blocks
==794467==    still reachable: 67,128,914 bytes in 349,964 blocks
==794467==                       of which reachable via heuristic:
==794467==                         newarray           : 496 bytes in 13 blocks
==794467==                         multipleinheritance: 136,888 bytes in 236 blocks
==794467==         suppressed: 16 bytes in 1 blocks
==794467== Rerun with --leak-check=full to see details of leaked memory
==794467==
==794467== For lists of detected and suppressed errors, rerun with: -s
==794467== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)```

**Comment by alphafox02** [comment]
Have noticed this on 20.04 using either a 20.04 based appimage I put together, built with the blsd script, or installed directly from source. Ive also been able to make it happen by opening a subcarrier inspector.

However, I cannot reproduce it with the latest 18.04 based appimage created on here or with the fork I put together. Could you try with this?

 https://github.com/BatchDrake/SigDigger/actions/runs/1508709009

**Comment by jedi7** [comment]
I'm not using Ubuntu. So I'm compiling it manually by using aur. I updated info about build in ticket.

**Comment by alphafox02** [comment]
Could you try the appimage though on your distro just to see if it does the same thing?

**Comment by BatchDrake** [comment]
This looks like a locking problem in Suscan I may have fixed earlier today. Could you rebuild and try again?

**Comment by jedi7** [comment]
Awesome :) you fixed it, thanks

**Comment by jedi7** [comment]
ok the issue is solved only partialy. New steps to reproduce:

1) start receiver
2) move to bookmark with modulation LSB (so change will be from FM)
3) see segfault

**Comment by BatchDrake** [comment]
I believe I've just fixed it. It was some weird memory alignment-related issue in sigutils.

**Comment by jedi7** [comment]
fixed, thanks! :)
