### ISSUE TITLE
Unit test list is outdated

### ISSUE THREAD

**Issue by BatchDrake** [BatchDrake/sigutils#3]
There has been a bunch of features since the last unit test was written (baudrate detection, see https://github.com/BatchDrake/sigutils/commit/9216655ff535535493210d4225cb2563bb602e85#diff-796031913b2c18ce3e0e367f00710f2e). New tests should be written to cover what has been implemented so far.

**Comment by antoniovazquezblanco** [comment]
What would you like to test exactly?

**Comment by antoniovazquezblanco** [comment]
This issue seems outdated. New issues with particular tests requests should be created...
