### ISSUE TITLE
Fix unit test failures

### ISSUE THREAD

**Issue by BatchDrake** [BatchDrake/sigutils#4]
The following tests are failing and should be investigated:

- `su_test_agc_steady_falling` (test ID: 4)
- `su_test_costas_block` (test ID: 14)
- `su_test_cdr_block` (test ID: 19)

**Comment by antoniovazquezblanco** [comment]
Old tests have been deleted. What exactly would you like to see tested?

**Comment by antoniovazquezblanco** [comment]
This issue seems outdated. New issues with particular tests requests should be created...
