### ISSUE TITLE
Unit tests refactor

### ISSUE THREAD

**Issue by antoniovazquezblanco** [BatchDrake/sigutils#44]
At some point I would like to contribute by refactoring the test infraestructure in this repo. Looking at suitable frameworks I found https://libcheck.github.io/check/ wich seemd like adecuated for the job but I have not used it. I would like some input and or feedback if anyone has experience with it or with any other C alternative.

Thanks

**Comment by BatchDrake** [comment]
Please go ahead. The current unit test infrastructure is old and deprecated, and it was more like an ad-hoc code to test the earliest APIs of the library. Sigutils is rather mature now, and something more serious is more than welcome.

**Comment by antoniovazquezblanco** [comment]
New testing infraestructure is in place!
